package com.vod.db.mapper;

import com.vod.db.model.AccountInfo;
import com.vod.db.model.AccountInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int countByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int deleteByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int insert(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int insertSelective(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    List<AccountInfo> selectByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    AccountInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int updateByExample(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int updateByPrimaryKeySelective(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountinfo
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    int updateByPrimaryKey(AccountInfo record);
}