package com.vod.db.mapper;

import com.vod.db.model.UserInfoLog;
import com.vod.db.model.UserInfoLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int countByExample(UserInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int deleteByExample(UserInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int insert(UserInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int insertSelective(UserInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    List<UserInfoLog> selectByExample(UserInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    UserInfoLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserInfoLog record, @Param("example") UserInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int updateByExample(@Param("record") UserInfoLog record, @Param("example") UserInfoLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int updateByPrimaryKeySelective(UserInfoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfolog
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    int updateByPrimaryKey(UserInfoLog record);
}