package com.vod.db.model;

import java.util.Date;

public class AccountInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.id
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.parentId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.accountType
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.loginId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.customerCode
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.accountName
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.nonceToken
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String nonceToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.passwordSalt
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String passwordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.passwordHash
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String passwordHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.phoneNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.contactNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String contactNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.faxNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String faxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.altEmail
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String altEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.siteLink
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String siteLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.webchatId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String webchatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.qqId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String qqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.accountStatus
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private String accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.createdDate
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.createdBy
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.modifiedDate
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountinfo.modifiedBy
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    private Long modifiedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.id
     *
     * @return the value of accountinfo.id
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.id
     *
     * @param id the value for accountinfo.id
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.parentId
     *
     * @return the value of accountinfo.parentId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.parentId
     *
     * @param parentId the value for accountinfo.parentId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.accountType
     *
     * @return the value of accountinfo.accountType
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.accountType
     *
     * @param accountType the value for accountinfo.accountType
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.loginId
     *
     * @return the value of accountinfo.loginId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.loginId
     *
     * @param loginId the value for accountinfo.loginId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.customerCode
     *
     * @return the value of accountinfo.customerCode
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.customerCode
     *
     * @param customerCode the value for accountinfo.customerCode
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.accountName
     *
     * @return the value of accountinfo.accountName
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.accountName
     *
     * @param accountName the value for accountinfo.accountName
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.nonceToken
     *
     * @return the value of accountinfo.nonceToken
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getNonceToken() {
        return nonceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.nonceToken
     *
     * @param nonceToken the value for accountinfo.nonceToken
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setNonceToken(String nonceToken) {
        this.nonceToken = nonceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.passwordSalt
     *
     * @return the value of accountinfo.passwordSalt
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.passwordSalt
     *
     * @param passwordSalt the value for accountinfo.passwordSalt
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.passwordHash
     *
     * @return the value of accountinfo.passwordHash
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.passwordHash
     *
     * @param passwordHash the value for accountinfo.passwordHash
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.phoneNumber
     *
     * @return the value of accountinfo.phoneNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.phoneNumber
     *
     * @param phoneNumber the value for accountinfo.phoneNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.contactNumber
     *
     * @return the value of accountinfo.contactNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.contactNumber
     *
     * @param contactNumber the value for accountinfo.contactNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.faxNumber
     *
     * @return the value of accountinfo.faxNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.faxNumber
     *
     * @param faxNumber the value for accountinfo.faxNumber
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.altEmail
     *
     * @return the value of accountinfo.altEmail
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getAltEmail() {
        return altEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.altEmail
     *
     * @param altEmail the value for accountinfo.altEmail
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setAltEmail(String altEmail) {
        this.altEmail = altEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.siteLink
     *
     * @return the value of accountinfo.siteLink
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getSiteLink() {
        return siteLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.siteLink
     *
     * @param siteLink the value for accountinfo.siteLink
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setSiteLink(String siteLink) {
        this.siteLink = siteLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.webchatId
     *
     * @return the value of accountinfo.webchatId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getWebchatId() {
        return webchatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.webchatId
     *
     * @param webchatId the value for accountinfo.webchatId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setWebchatId(String webchatId) {
        this.webchatId = webchatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.qqId
     *
     * @return the value of accountinfo.qqId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getQqId() {
        return qqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.qqId
     *
     * @param qqId the value for accountinfo.qqId
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setQqId(String qqId) {
        this.qqId = qqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.accountStatus
     *
     * @return the value of accountinfo.accountStatus
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.accountStatus
     *
     * @param accountStatus the value for accountinfo.accountStatus
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.createdDate
     *
     * @return the value of accountinfo.createdDate
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.createdDate
     *
     * @param createdDate the value for accountinfo.createdDate
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.createdBy
     *
     * @return the value of accountinfo.createdBy
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.createdBy
     *
     * @param createdBy the value for accountinfo.createdBy
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.modifiedDate
     *
     * @return the value of accountinfo.modifiedDate
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.modifiedDate
     *
     * @param modifiedDate the value for accountinfo.modifiedDate
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountinfo.modifiedBy
     *
     * @return the value of accountinfo.modifiedBy
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public Long getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountinfo.modifiedBy
     *
     * @param modifiedBy the value for accountinfo.modifiedBy
     *
     * @mbggenerated Fri Dec 16 17:11:38 CST 2016
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
}