package com.vod.db.model;

import java.util.Date;

public class UserInfoLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfolog.id
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfolog.userInfoId
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    private Integer userInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfolog.amount
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfolog.time
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfolog.id
     *
     * @return the value of userinfolog.id
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfolog.id
     *
     * @param id the value for userinfolog.id
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfolog.userInfoId
     *
     * @return the value of userinfolog.userInfoId
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    public Integer getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfolog.userInfoId
     *
     * @param userInfoId the value for userinfolog.userInfoId
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfolog.amount
     *
     * @return the value of userinfolog.amount
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfolog.amount
     *
     * @param amount the value for userinfolog.amount
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfolog.time
     *
     * @return the value of userinfolog.time
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfolog.time
     *
     * @param time the value for userinfolog.time
     *
     * @mbggenerated Tue Apr 25 11:21:41 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }
}